import type { Metadata } from "next";
// import "bootstrap/dist/css/bootstrap.min.css";
import "@/css/style.css";
import Script from "next/script";

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en">
			<head>
				<meta charSet="UTF-8" />

				<link
					rel="stylesheet"
					href="https://fonts.cdnfonts.com/css/tenorite"
					crossOrigin="anonymous"
				/>

				<link
					rel="stylesheet"
					href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.1/dist/css/bootstrap.min.css"
				/>

				<link
					rel="stylesheet"
					href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.10.2/css/all.css"
				/>
				<meta
					name="viewport"
					content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0"
				/>

				<link rel="stylesheet" href="https://use.typekit.net/oov2wcw.css" />
			</head>
			<body>{children}</body>
		</html>
	);
}
